const SCRIPTS = [  {
    id: "infinity-hub",
    name: "Infinity Hub",
    game: "Blox Fruits",
    category: "Hub",
    emoji: "🍉",
    gradient: "linear-gradient(135deg,#7a1050,#3d0a4d 45%,#0a2d6e)",
    price: 149,
    oldPrice: 249,
    rating: 4.9,
    sales: 4820,
    updates: "Weekly Updates",
    bestseller: true,
    new: false,
    featured: true,
    desc: "A 24/7 fully automated hub for Blox Fruits. Includes optimizations for every fruit, boss and live event.",
    features: [
      "Infinity Hub main module",
      "Infinity Hub profile presets",
      "Hub teleport list",
      "Loadout locker",
      "Quick-launch dock",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Unlimited: active on 2 devices"
    ]
  },
  {
    id: "arachnid-aim",
    name: "Arachnid Aimbot",
    game: "Arsenal",
    category: "Combat",
    emoji: "🕷️",
    gradient: "linear-gradient(135deg,#8f0f1f,#4a0712 40%,#1a0510)",
    price: 99,
    oldPrice: 0,
    rating: 4.8,
    sales: 9100,
    updates: "Monthly Updates",
    bestseller: false,
    new: false,
    featured: true,
    desc: "Competitive-grade aimbot for Arsenal. Built with account safety as a top priority.",
    features: [
      "Arachnid Aimbot main module",
      "Arachnid Aimbot profile presets",
      "Combo recorder",
      "Hit confirm assist",
      "Target priority AI",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 1 device"
    ]
  },
  {
    id: "mystic-race",
    name: "Mystic Race",
    game: "Anime Adventures",
    category: "Farm",
    emoji: "🌀",
    gradient: "linear-gradient(135deg,#2a1d6e,#12094a 40%,#02102a)",
    price: 79,
    oldPrice: 119,
    rating: 4.6,
    sales: 2540,
    updates: "Monthly Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Auto legendary pull and portal farm bot for Anime Adventures.",
    features: [
      "Mystic Race main module",
      "Mystic Race profile presets",
      "Auto farm loop",
      "Loot magnet radius",
      "Egg hatch chain",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 1 device"
    ]
  },
  {
    id: "blaze-admin",
    name: "Blaze Admin",
    game: "Private Servers",
    category: "Admin",
    emoji: "⚡",
    gradient: "linear-gradient(135deg,#2e0964,#5a0f8f 50%,#ff5f1f)",
    price: 199,
    oldPrice: 299,
    rating: 5.0,
    sales: 3180,
    updates: "Constant Updates",
    bestseller: true,
    new: false,
    featured: true,
    desc: "A fully loaded admin panel for private servers. Delivers over 500 commands and script protection.",
    features: [
      "Blaze Admin main module",
      "Blaze Admin profile presets",
      "Command runner",
      "Permissions presets",
      "World loop timer",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support"
    ]
  },
  {
    id: "neon-speed",
    name: "Neon Speed",
    game: "Universal",
    category: "Universal",
    emoji: "🚀",
    gradient: "linear-gradient(135deg,#002d6e,#0062ff 50%,#00f0ff)",
    price: 49,
    oldPrice: 0,
    rating: 4.5,
    sales: 15200,
    updates: "Rare Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Universal speed and farm script working in many walk-speed simulator games.",
    features: [
      "Neon Speed main module",
      "Neon Speed profile presets",
      "Universal bridge",
      "Hotkey editor",
      "FPS lite mode",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Unlimited: active on 2 devices"
    ]
  },
  {
    id: "crystal-hub",
    name: "Crystal Hub",
    game: "Legends of Speed",
    category: "Hub",
    emoji: "💎",
    gradient: "linear-gradient(135deg,#0a5d5d,#0f8f8f 45%,#00c2ff)",
    price: 89,
    oldPrice: 139,
    rating: 4.7,
    sales: 2290,
    updates: "Monthly Updates",
    bestseller: false,
    new: true,
    featured: false,
    desc: "Next-gen auto farm center for Legends of Speed.",
    features: [
      "Crystal Hub main module",
      "Crystal Hub profile presets",
      "Hub teleport list",
      "Loadout locker",
      "Quick-launch dock",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 1 device"
    ]
  },
  {
    id: "void-extractor",
    name: "Void Extractor",
    game: "Pet Simulator X",
    category: "Farm",
    emoji: "👾",
    gradient: "linear-gradient(135deg,#12042a,#2e0a58 45%,#7a1fbf)",
    price: 119,
    oldPrice: 0,
    rating: 4.7,
    sales: 6740,
    updates: "Weekly Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Auto wealth and pet farm system for Pet Simulator X.",
    features: [
      "Void Extractor main module",
      "Void Extractor profile presets",
      "Auto farm loop",
      "Loot magnet radius",
      "Egg hatch chain",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 1 device"
    ]
  },
  {
    id: "shadow-ninja",
    name: "Shadow Ninja",
    game: "Shindo Life",
    category: "Combat",
    emoji: "🥷",
    gradient: "linear-gradient(135deg,#08060f,#1a1030 45%,#3d1f66)",
    price: 139,
    oldPrice: 189,
    rating: 4.8,
    sales: 1980,
    updates: "Monthly Updates",
    bestseller: false,
    new: true,
    featured: true,
    desc: "Full automation and farm bot for shadow clans in Shindo Life.",
    features: [
      "Shadow Ninja main module",
      "Shadow Ninja profile presets",
      "Combo recorder",
      "Hit confirm assist",
      "Target priority AI",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Unlimited: active on 2 devices"
    ]
  },
  {
    id: "quantum-trade",
    name: "Quantum Trader",
    game: "Grand Piece Online",
    category: "Hub",
    emoji: "⛵",
    gradient: "linear-gradient(135deg,#0b3d66,#0a6b8f 50%,#00d2d3)",
    price: 109,
    oldPrice: 159,
    rating: 4.4,
    sales: 1430,
    updates: "Rare Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Auto quest, fragment and island travel assistant for Grand Piece Online.",
    features: [
      "Quantum Trader main module",
      "Quantum Trader profile presets",
      "Hub teleport list",
      "Loadout locker",
      "Quick-launch dock",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 1 device"
    ]
  },
  {
    id: "matrix-pro",
    name: "Matrix Pro",
    game: "Doors",
    category: "Universal",
    emoji: "🟰",
    gradient: "linear-gradient(135deg,#03030a,#0a0a1f 40%,#00ff95)",
    price: 59,
    oldPrice: 0,
    rating: 4.6,
    sales: 8900,
    updates: "Monthly Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Floor complete cheat for Doors and similar horror games.",
    features: [
      "Matrix Pro main module",
      "Matrix Pro profile presets",
      "Universal bridge",
      "Hotkey editor",
      "FPS lite mode",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Unlimited: active on 1 device"
    ]
  },
  {
    id: "blade-fruit-hub",
    name: "Blade Fruit Hub",
    game: "Blox Fruits",
    category: "Hub",
    emoji: "🗡️",
    gradient: "linear-gradient(135deg,#70103a,#3d0a4d 45%,#0a2d6e)",
    price: 159,
    oldPrice: 229,
    rating: 4.8,
    sales: 7340,
    updates: "Weekly Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Blade-focused loadout hub for Blox Fruits. Sets up full sword builds with one click.",
    features: [
      "Blade Fruit Hub main module",
      "Blade Fruit Hub profile presets",
      "Hub teleport list",
      "Loadout locker",
      "Quick-launch dock",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Unlimited: active on 2 devices"
    ]
  },
  {
    id: "dragon-v2-hub",
    name: "Dragon V2 Hub",
    game: "Blox Fruits",
    category: "Hub",
    emoji: "🐉",
    gradient: "linear-gradient(135deg,#3d0a0a,#7a1010 45%,#ff5f1f)",
    price: 189,
    oldPrice: 279,
    rating: 4.9,
    sales: 5120,
    updates: "Daily Updates",
    bestseller: false,
    new: true,
    featured: true,
    desc: "The ultimate Dragon V2 experience. Farms, raids and boss events fully automated.",
    features: [
      "Dragon V2 Hub main module",
      "Dragon V2 Hub profile presets",
      "Hub teleport list",
      "Loadout locker",
      "Quick-launch dock",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Unlimited: active on 3 devices"
    ]
  },
  {
    id: "sea-beast-hunter-x",
    name: "Sea Beast Hunter X",
    game: "Blox Fruits",
    category: "Farm",
    emoji: "🌊",
    gradient: "linear-gradient(135deg,#062a4a,#0a5d8f 50%,#00d2d3)",
    price: 129,
    oldPrice: 189,
    rating: 4.7,
    sales: 6120,
    updates: "Weekly Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Auto sea beast and ship raid killer. Rotates islands to find beasts fast.",
    features: [
      "Sea Beast Hunter X main module",
      "Sea Beast Hunter X profile presets",
      "Auto farm loop",
      "Loot magnet radius",
      "Egg hatch chain",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 1 device"
    ]
  },
  {
    id: "fruit-finder-pro",
    name: "Fruit Finder Pro",
    game: "Blox Fruits",
    category: "Universal",
    emoji: "🍈",
    gradient: "linear-gradient(135deg,#1d5500,#2e8f00 45%,#00d26a)",
    price: 79,
    oldPrice: 0,
    rating: 4.5,
    sales: 9880,
    updates: "Monthly Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Scans the map for spawned fruits and teleports instantly. Great for stock mains.",
    features: [
      "Fruit Finder Pro main module",
      "Fruit Finder Pro profile presets",
      "Universal bridge",
      "Hotkey editor",
      "FPS lite mode",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Unlimited: active on 1 device"
    ]
  },
  {
    id: "awakened-trainer",
    name: "Awakened Trainer",
    game: "Blox Fruits",
    category: "Combat",
    emoji: "💢",
    gradient: "linear-gradient(135deg,#6e0a2a,#8f0f3d 45%,#2a0a4d)",
    price: 99,
    oldPrice: 139,
    rating: 4.6,
    sales: 4480,
    updates: "Monthly Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Auto-train your awakened moves in the safest farming spots available.",
    features: [
      "Awakened Trainer main module",
      "Awakened Trainer profile presets",
      "Combo recorder",
      "Hit confirm assist",
      "Target priority AI",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 1 device"
    ]
  },
  {
    id: "racial-v4-master",
    name: "Racial V4 Master",
    game: "Blox Fruits",
    category: "Farm",
    emoji: "🧬",
    gradient: "linear-gradient(135deg,#3d0a6e,#6e1fbf 50%,#c06fff)",
    price: 119,
    oldPrice: 0,
    rating: 4.6,
    sales: 3010,
    updates: "Monthly Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Full V4 race awakening automation: trials, curses and achievements handled.",
    features: [
      "Racial V4 Master main module",
      "Racial V4 Master profile presets",
      "Auto farm loop",
      "Loot magnet radius",
      "Egg hatch chain",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 1 device"
    ]
  },
  {
    id: "boss-stomp",
    name: "Boss Stomp",
    game: "Blox Fruits",
    category: "Combat",
    emoji: "👊",
    gradient: "linear-gradient(135deg,#551006,#8f1f0f 45%,#e0561f)",
    price: 89,
    oldPrice: 0,
    rating: 4.4,
    sales: 3870,
    updates: "Monthly Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Shreds boss NPCs with rotation-aware combos and auto-dodge positioning.",
    features: [
      "Boss Stomp main module",
      "Boss Stomp profile presets",
      "Combo recorder",
      "Hit confirm assist",
      "Target priority AI",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 1 device"
    ]
  },
  {
    id: "auto-quest-blox",
    name: "Auto Quest Blox",
    game: "Blox Fruits",
    category: "Farm",
    emoji: "📜",
    gradient: "linear-gradient(135deg,#0a2d6e,#1f5dbf 50%,#00c2ff)",
    price: 69,
    oldPrice: 0,
    rating: 4.5,
    sales: 7210,
    updates: "Weekly Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Takes quests, farms targets and turns them in by itself. Zero touching required.",
    features: [
      "Auto Quest Blox main module",
      "Auto Quest Blox profile presets",
      "Auto farm loop",
      "Loot magnet radius",
      "Egg hatch chain",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Unlimited: active on 2 devices"
    ]
  },
  {
    id: "tiki-villain-hunter",
    name: "Tiki Villain Hunter",
    game: "Blox Fruits",
    category: "Combat",
    emoji: "🪓",
    gradient: "linear-gradient(135deg,#0a3d1f,#125d33 45%,#00ff95)",
    price: 109,
    oldPrice: 0,
    rating: 4.7,
    sales: 2560,
    updates: "Weekly Updates",
    bestseller: false,
    new: true,
    featured: false,
    desc: "Hunts Tiki villains across islands with respawn timing prediction.",
    features: [
      "Tiki Villain Hunter main module",
      "Tiki Villain Hunter profile presets",
      "Combo recorder",
      "Hit confirm assist",
      "Target priority AI",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 2 devices"
    ]
  },
  {
    id: "sailor-gp-farm",
    name: "Sailor GP Farm",
    game: "Blox Fruits",
    category: "Farm",
    emoji: "⛵",
    gradient: "linear-gradient(135deg,#0b3d66,#0a6b8f 45%,#00d2d3)",
    price: 79,
    oldPrice: 119,
    rating: 4.4,
    sales: 3430,
    updates: "Monthly Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Sail-orbit farm loops for GP, bones and captain quests while you idle.",
    features: [
      "Sailor GP Farm main module",
      "Sailor GP Farm profile presets",
      "Auto farm loop",
      "Loot magnet radius",
      "Egg hatch chain",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 1 device"
    ]
  },
  {
    id: "quick-draw-aim",
    name: "Quick Draw Aim",
    game: "Arsenal",
    category: "Combat",
    emoji: "🔫",
    gradient: "linear-gradient(135deg,#1a0510,#4a0712 45%,#8f0f1f)",
    price: 89,
    oldPrice: 0,
    rating: 4.6,
    sales: 5230,
    updates: "Monthly Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Fast-lock aim assist tuned for quick-draw gunfights and moving targets.",
    features: [
      "Quick Draw Aim main module",
      "Quick Draw Aim profile presets",
      "Combo recorder",
      "Hit confirm assist",
      "Target priority AI",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 1 device"
    ]
  },
  {
    id: "trigger-finger",
    name: "Trigger Finger",
    game: "Arsenal",
    category: "Combat",
    emoji: "🖱️",
    gradient: "linear-gradient(135deg,#0a0a1f,#1f1f4a 45%,#6e2dbf)",
    price: 59,
    oldPrice: 0,
    rating: 4.3,
    sales: 8940,
    updates: "Monthly Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Instant trigger on target with recoil compensation. Lightweight and smooth.",
    features: [
      "Trigger Finger main module",
      "Trigger Finger profile presets",
      "Combo recorder",
      "Hit confirm assist",
      "Target priority AI",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Unlimited: active on 1 device"
    ]
  },
  {
    id: "recoil-killer",
    name: "Recoil Killer",
    game: "Arsenal",
    category: "Combat",
    emoji: "🎯",
    gradient: "linear-gradient(135deg,#0a1f2a,#0a3d5d 45%,#0a8fbf)",
    price: 69,
    oldPrice: 0,
    rating: 4.4,
    sales: 6120,
    updates: "Rare Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Eliminates visual spray so every burst lands where it should.",
    features: [
      "Recoil Killer main module",
      "Recoil Killer profile presets",
      "Combo recorder",
      "Hit confirm assist",
      "Target priority AI",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 1 device"
    ]
  },
  {
    id: "silent-strike-x",
    name: "Silent Strike X",
    game: "Arsenal",
    category: "Combat",
    emoji: "🥷",
    gradient: "linear-gradient(135deg,#08060f,#1a1030 45%,#3d1f66)",
    price: 129,
    oldPrice: 179,
    rating: 4.8,
    sales: 3340,
    updates: "Weekly Updates",
    bestseller: false,
    new: false,
    featured: true,
    desc: "Competitive silent-aim package with movement jitter resistance.",
    features: [
      "Silent Strike X main module",
      "Silent Strike X profile presets",
      "Combo recorder",
      "Hit confirm assist",
      "Target priority AI",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Unlimited: active on 2 devices"
    ]
  },
  {
    id: "headshot-master",
    name: "Headshot Master",
    game: "Arsenal",
    category: "Combat",
    emoji: "💀",
    gradient: "linear-gradient(135deg,#2a0a0a,#5d1212 45%,#a01f1f)",
    price: 109,
    oldPrice: 159,
    rating: 4.7,
    sales: 4505,
    updates: "Monthly Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Headshot-priority aim with body-hit fallback during critical fights.",
    features: [
      "Headshot Master main module",
      "Headshot Master profile presets",
      "Combo recorder",
      "Hit confirm assist",
      "Target priority AI",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 1 device"
    ]
  },
  {
    id: "wallbang-assist",
    name: "Wallbang Assist",
    game: "Arsenal",
    category: "Combat",
    emoji: "🧱",
    gradient: "linear-gradient(135deg,#0a2d1f,#125d33 45%,#2e8f5d)",
    price: 49,
    oldPrice: 0,
    rating: 4.2,
    sales: 3870,
    updates: "Rare Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Lines up common wallbang angles so you never miss a low-health frag.",
    features: [
      "Wallbang Assist main module",
      "Wallbang Assist profile presets",
      "Combo recorder",
      "Hit confirm assist",
      "Target priority AI",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 1 device"
    ]
  },
  {
    id: "portal-farmer-x",
    name: "Portal Farmer X",
    game: "Anime Adventures",
    category: "Farm",
    emoji: "🌀",
    gradient: "linear-gradient(135deg,#2a1d6e,#12094a 45%,#02102a)",
    price: 99,
    oldPrice: 149,
    rating: 4.6,
    sales: 3120,
    updates: "Monthly Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Auto portal farm with rarity filter and endless reroll protection.",
    features: [
      "Portal Farmer X main module",
      "Portal Farmer X profile presets",
      "Auto farm loop",
      "Loot magnet radius",
      "Egg hatch chain",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 2 devices"
    ]
  },
  {
    id: "summon-reroller",
    name: "Summon Reroller",
    game: "Anime Adventures",
    category: "Universal",
    emoji: "🎴",
    gradient: "linear-gradient(135deg,#4a0a3d,#8f1f7a 45%,#e056c0)",
    price: 79,
    oldPrice: 0,
    rating: 4.5,
    sales: 4890,
    updates: "Monthly Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Rerolls summons until it finds the unit you want, then alerts you.",
    features: [
      "Summon Reroller main module",
      "Summon Reroller profile presets",
      "Universal bridge",
      "Hotkey editor",
      "FPS lite mode",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Unlimited: active on 2 devices"
    ]
  },
  {
    id: "quest-automator-anime",
    name: "Quest Automator",
    game: "Anime Adventures",
    category: "Farm",
    emoji: "📋",
    gradient: "linear-gradient(135deg,#0a3d6e,#1f6ebf 45%,#00c2ff)",
    price: 89,
    oldPrice: 0,
    rating: 4.6,
    sales: 2210,
    updates: "Weekly Updates",
    bestseller: false,
    new: true,
    featured: false,
    desc: "Completes story and event quests hands-free with smart unit rotation.",
    features: [
      "Quest Automator main module",
      "Quest Automator profile presets",
      "Auto farm loop",
      "Loot magnet radius",
      "Egg hatch chain",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 1 device"
    ]
  },
  {
    id: "raid-slayer-anime",
    name: "Raid Slayer",
    game: "Anime Adventures",
    category: "Combat",
    emoji: "⚔️",
    gradient: "linear-gradient(135deg,#3d0a0a,#7a1212 45%,#e0561f)",
    price: 119,
    oldPrice: 169,
    rating: 4.7,
    sales: 1780,
    updates: "Monthly Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Raid-focused bot that clears waves and bosses with placement intelligence.",
    features: [
      "Raid Slayer main module",
      "Raid Slayer profile presets",
      "Combo recorder",
      "Hit confirm assist",
      "Target priority AI",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 1 device"
    ]
  },
  {
    id: "evolution-buddy",
    name: "Evolution Buddy",
    game: "Anime Adventures",
    category: "Farm",
    emoji: "🦋",
    gradient: "linear-gradient(135deg,#0a4a2a,#0f7a45 45%,#00d26a)",
    price: 69,
    oldPrice: 0,
    rating: 4.4,
    sales: 2650,
    updates: "Rare Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Tracks evolution materials and farms missing items automatically.",
    features: [
      "Evolution Buddy main module",
      "Evolution Buddy profile presets",
      "Auto farm loop",
      "Loot magnet radius",
      "Egg hatch chain",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 1 device"
    ]
  },
  {
    id: "tailed-beast-hunter",
    name: "Tailed Beast Hunter",
    game: "Shindo Life",
    category: "Combat",
    emoji: "🦊",
    gradient: "linear-gradient(135deg,#3d1f00,#7a3d0a 45%,#ffae42)",
    price: 139,
    oldPrice: 199,
    rating: 4.8,
    sales: 2940,
    updates: "Weekly Updates",
    bestseller: true,
    new: false,
    featured: false,
    desc: "Hunts all tailed beasts with sub-skill synergy and mount tracking.",
    features: [
      "Tailed Beast Hunter main module",
      "Tailed Beast Hunter profile presets",
      "Combo recorder",
      "Hit confirm assist",
      "Target priority AI",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Unlimited: active on 2 devices"
    ]
  },
  {
    id: "scroll-farm",
    name: "Scroll Farm",
    game: "Shindo Life",
    category: "Farm",
    emoji: "📜",
    gradient: "linear-gradient(135deg,#0a1f4a,#1f3d8f 45%,#2e6eff)",
    price: 99,
    oldPrice: 149,
    rating: 4.6,
    sales: 3320,
    updates: "Monthly Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Farms scrolls across maps with drop-tracking and server swapping.",
    features: [
      "Scroll Farm main module",
      "Scroll Farm profile presets",
      "Auto farm loop",
      "Loot magnet radius",
      "Egg hatch chain",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 1 device"
    ]
  },
  {
    id: "clan-war-bot",
    name: "Clan War Bot",
    game: "Shindo Life",
    category: "Combat",
    emoji: "🗡️",
    gradient: "linear-gradient(135deg,#2a0a1f,#5d1040 45%,#a01f70)",
    price: 149,
    oldPrice: 219,
    rating: 4.7,
    sales: 1870,
    updates: "Weekly Updates",
    bestseller: false,
    new: false,
    featured: true,
    desc: "Clan battle automation with tactical positioning and flag control.",
    features: [
      "Clan War Bot main module",
      "Clan War Bot profile presets",
      "Combo recorder",
      "Hit confirm assist",
      "Target priority AI",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Unlimited: active on 2 devices"
    ]
  },
  {
    id: "zanpakuto-maxer",
    name: "Zanpakuto Maxer",
    game: "Shindo Life",
    category: "Farm",
    emoji: "⚡",
    gradient: "linear-gradient(135deg,#0a2a4a,#1f4a8f 45%,#2e8fff)",
    price: 129,
    oldPrice: 0,
    rating: 4.6,
    sales: 2240,
    updates: "Monthly Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Maxes every Zanpakuto with SSD-efficient farm routing.",
    features: [
      "Zanpakuto Maxer main module",
      "Zanpakuto Maxer profile presets",
      "Auto farm loop",
      "Loot magnet radius",
      "Egg hatch chain",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 1 device"
    ]
  },
  {
    id: "mode-switcher-shindo",
    name: "Mode Switcher",
    game: "Shindo Life",
    category: "Farm",
    emoji: "🔄",
    gradient: "linear-gradient(135deg,#1f0a3d,#4a1f7a 45%,#8f5dbf)",
    price: 89,
    oldPrice: 0,
    rating: 4.4,
    sales: 2610,
    updates: "Rare Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Auto-switches release modes to keep buffs permanent during long farms.",
    features: [
      "Mode Switcher main module",
      "Mode Switcher profile presets",
      "Auto farm loop",
      "Loot magnet radius",
      "Egg hatch chain",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 1 device"
    ]
  },
  {
    id: "auto-clicker-pro",
    name: "Auto Clicker Pro",
    game: "Universal",
    category: "Universal",
    emoji: "🖱️",
    gradient: "linear-gradient(135deg,#0a0a0a,#2a2a2a 45%,#5d5d5d)",
    price: 39,
    oldPrice: 0,
    rating: 4.5,
    sales: 13980,
    updates: "Rare Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "CPS-randomized auto clicker with jitterless idle performance.",
    features: [
      "Auto Clicker Pro main module",
      "Auto Clicker Pro profile presets",
      "Universal bridge",
      "Hotkey editor",
      "FPS lite mode",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Unlimited: active on 2 devices"
    ]
  },
  {
    id: "speed-runner-x",
    name: "Speed Runner X",
    game: "Universal",
    category: "Universal",
    emoji: "🏃",
    gradient: "linear-gradient(135deg,#0a3d1f,#1f6e3d 45%,#2e8f5d)",
    price: 49,
    oldPrice: 0,
    rating: 4.5,
    sales: 11240,
    updates: "Rare Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Walk-speed and jump multiplier for simulators. Drag-resistant engine.",
    features: [
      "Speed Runner X main module",
      "Speed Runner X profile presets",
      "Universal bridge",
      "Hotkey editor",
      "FPS lite mode",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Unlimited: active on 2 devices"
    ]
  },
  {
    id: "jump-booster",
    name: "Jump Booster",
    game: "Universal",
    category: "Universal",
    emoji: "🦘",
    gradient: "linear-gradient(135deg,#0a4a2a,#0f7a45 45%,#00d26a)",
    price: 29,
    oldPrice: 0,
    rating: 4.3,
    sales: 16450,
    updates: "Rare Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Simple jump-power multiplier for obbies and simulators.",
    features: [
      "Jump Booster main module",
      "Jump Booster profile presets",
      "Universal bridge",
      "Hotkey editor",
      "FPS lite mode",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Unlimited: active on 2 devices"
    ]
  },
  {
    id: "loot-grabber",
    name: "Loot Grabber",
    game: "Universal",
    category: "Universal",
    emoji: "💰",
    gradient: "linear-gradient(135deg,#3d2a0a,#6e4a12 45%,#ffae42)",
    price: 59,
    oldPrice: 0,
    rating: 4.4,
    sales: 7810,
    updates: "Rare Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Broad-range loot vacuum that grabs coins and rewards around you.",
    features: [
      "Loot Grabber main module",
      "Loot Grabber profile presets",
      "Universal bridge",
      "Hotkey editor",
      "FPS lite mode",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 1 device"
    ]
  },
  {
    id: "anti-afk-x",
    name: "Anti-AFK X",
    game: "Universal",
    category: "Universal",
    emoji: "😴",
    gradient: "linear-gradient(135deg,#0a0a1f,#1f1f3d 45%,#3d3d6e)",
    price: 19,
    oldPrice: 0,
    rating: 4.2,
    sales: 19720,
    updates: "Rare Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Micro-movement and chat wiggle so you never get kicked while idle.",
    features: [
      "Anti-AFK X main module",
      "Anti-AFK X profile presets",
      "Universal bridge",
      "Hotkey editor",
      "FPS lite mode",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Unlimited: active on 3 devices"
    ]
  },
  {
    id: "macro-recorder",
    name: "Macro Recorder",
    game: "Universal",
    category: "Universal",
    emoji: "🎬",
    gradient: "linear-gradient(135deg,#2a0a3d,#4a1f7a 45%,#8f5dbf)",
    price: 69,
    oldPrice: 109,
    rating: 4.6,
    sales: 4480,
    updates: "Monthly Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Records keypress loops and replays them with randomized timing.",
    features: [
      "Macro Recorder main module",
      "Macro Recorder profile presets",
      "Universal bridge",
      "Hotkey editor",
      "FPS lite mode",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 1 device"
    ]
  },
  {
    id: "teleport-helper",
    name: "Teleport Helper",
    game: "Universal",
    category: "Universal",
    emoji: "🌀",
    gradient: "linear-gradient(135deg,#0a1f3d,#1f4a8f 45%,#2e8fff)",
    price: 79,
    oldPrice: 0,
    rating: 4.4,
    sales: 6120,
    updates: "Rare Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Waypoint teleport across any map with saved coordinate presets.",
    features: [
      "Teleport Helper main module",
      "Teleport Helper profile presets",
      "Universal bridge",
      "Hotkey editor",
      "FPS lite mode",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Unlimited: active on 2 devices"
    ]
  },
  {
    id: "npc-talker",
    name: "NPC Talker",
    game: "Universal",
    category: "Universal",
    emoji: "💬",
    gradient: "linear-gradient(135deg,#0a3d3d,#0f6e6e 45%,#00d2d3)",
    price: 49,
    oldPrice: 0,
    rating: 4.3,
    sales: 5340,
    updates: "Rare Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Auto walks to NPCs and talks to them on a timer loop.",
    features: [
      "NPC Talker main module",
      "NPC Talker profile presets",
      "Universal bridge",
      "Hotkey editor",
      "FPS lite mode",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 1 device"
    ]
  },
  {
    id: "target-lock-x",
    name: "Target Lock X",
    game: "Universal",
    category: "Combat",
    emoji: "🎯",
    gradient: "linear-gradient(135deg,#2a0a0a,#5d1212 45%,#e0561f)",
    price: 89,
    oldPrice: 129,
    rating: 4.6,
    sales: 8840,
    updates: "Monthly Updates",
    bestseller: false,
    new: false,
    featured: true,
    desc: "Universal target lock with shared spotlight for any combat game.",
    features: [
      "Target Lock X main module",
      "Target Lock X profile presets",
      "Combo recorder",
      "Hit confirm assist",
      "Target priority AI",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Unlimited: active on 2 devices"
    ]
  },
  {
    id: "spawn-tracer",
    name: "Spawn Tracer",
    game: "Universal",
    category: "Universal",
    emoji: "🛰️",
    gradient: "linear-gradient(135deg,#0a2d2d,#0a5d5d 45%,#00ff95)",
    price: 59,
    oldPrice: 0,
    rating: 4.3,
    sales: 3980,
    updates: "Rare Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Draws glowing tracer lines to recently spawned entities near you.",
    features: [
      "Spawn Tracer main module",
      "Spawn Tracer profile presets",
      "Universal bridge",
      "Hotkey editor",
      "FPS lite mode",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 1 device"
    ]
  },
  {
    id: "free-cam-pro",
    name: "Free Cam Pro",
    game: "Universal",
    category: "Universal",
    emoji: "🎥",
    gradient: "linear-gradient(135deg,#0a0a2a,#2a2a5d 45%,#5d5dbf)",
    price: 45,
    oldPrice: 0,
    rating: 4.4,
    sales: 4570,
    updates: "Rare Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Detached cinematic camera for exploring the whole map safely.",
    features: [
      "Free Cam Pro main module",
      "Free Cam Pro profile presets",
      "Universal bridge",
      "Hotkey editor",
      "FPS lite mode",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 1 device"
    ]
  },
  {
    id: "xp-glyph",
    name: "XP Glyph",
    game: "Universal",
    category: "Universal",
    emoji: "✨",
    gradient: "linear-gradient(135deg,#4a0a6e,#6e1fbf 45%,#c06fff)",
    price: 55,
    oldPrice: 0,
    rating: 4.5,
    sales: 6125,
    updates: "Monthly Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "Automated XP collection glyph that follows the safest farm path.",
    features: [
      "XP Glyph main module",
      "XP Glyph profile presets",
      "Universal bridge",
      "Hotkey editor",
      "FPS lite mode",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Active on 1 device"
    ]
  },
  {
    id: "server-suite-admin",
    name: "Server Suite",
    game: "Private Servers",
    category: "Admin",
    emoji: "🛠️",
    gradient: "linear-gradient(135deg,#1f0a3d,#3d1f7a 45%,#8f5dff)",
    price: 219,
    oldPrice: 329,
    rating: 4.9,
    sales: 2840,
    updates: "Constant Updates",
    bestseller: true,
    new: false,
    featured: false,
    desc: "The all-in-one admin suite: commands, economy, music and protection.",
    features: [
      "Server Suite main module",
      "Server Suite profile presets",
      "Command runner",
      "Permissions presets",
      "World loop timer",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support"
    ]
  },
  {
    id: "vip-admin",
    name: "VIP Admin",
    game: "Private Servers",
    category: "Admin",
    emoji: "👑",
    gradient: "linear-gradient(135deg,#3d2d0a,#6e4a12 45%,#ffae42)",
    price: 189,
    oldPrice: 289,
    rating: 4.8,
    sales: 1670,
    updates: "Constant Updates",
    bestseller: false,
    new: false,
    featured: false,
    desc: "VIP-focused admin with reserved commands and premium loadouts.",
    features: [
      "VIP Admin main module",
      "VIP Admin profile presets",
      "Command runner",
      "Permissions presets",
      "World loop timer",
      "24/7 stability",
      "Anti-detection layer",
      "Low RAM footprint",
      "Auto-update channel",
      "Multi-executor support",
      "Unlimited: active on 2 devices"
    ]
  }
];

const CATEGORIES = [
  { id: "all", label: "All" },
  { id: "Hub", label: "Hubs" },
  { id: "Combat", label: "Combat" },
  { id: "Farm", label: "Farm" },
  { id: "Admin", label: "Admin" },
  { id: "Universal", label: "Universal" }
];
const PRICE_LABEL = "RB$";
const ROBUX_LABEL = "RBX";
